#!/bin/bash
# Quick Start Guide for Smart Expense Tracker

echo "╔════════════════════════════════════════════════════════════╗"
echo "║        Smart Expense Tracker - Quick Start Guide          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 BUILD THE PROJECT:"
echo "   ./build.sh"
echo ""
echo "🚀 RUN THE APPLICATION:"
echo "   ./run.sh"
echo ""
echo "✓ VERIFY EVERYTHING:"
echo "   ./verify.sh"
echo ""
echo "📚 FEATURES:"
echo "   • Add, Edit, Delete Expenses"
echo "   • Dashboard with Statistics"
echo "   • Category Breakdown (Food, Travel, Entertainment, etc.)"
echo "   • Monthly Spending Charts (Pie, Bar, Line)"
echo "   • Export to CSV/JSON"
echo "   • Dark Mode Toggle"
echo "   • Auto-save Data"
echo ""
echo "🎮 CONTROLS:"
echo "   • Navigate using sidebar buttons"
echo "   • File → Export to save data externally"
echo "   • View → Dark Mode to toggle theme"
echo ""
echo "💾 DATA STORAGE:"
echo "   • Location: data/expenses.json"
echo "   • Auto-saved on exit"
echo "   • Auto-loaded on startup"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Status: ✅ All systems operational"
echo "═══════════════════════════════════════════════════════════"
